config/routes.rb
Rails.application.routes.draw do

  get 'charges/create'

  get 'charges/new'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  post 'order_complete' => 'cart#order_complete'

  post 'checkout' => 'cart#checkout'

  resources :orders
  resources :line_items
  devise_for :users
  resources :paintings
  
  root 'welcome#index'
  get 'contact' => 'welcome#contact'
  get 'sold' => 'welcome#sold'
  get 'for_sale' => 'welcome#for_sale'

end

app/models/painting.rb
class Painting < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	belongs_to :category
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]

  before_filter  :authenticate_user!, :except => [:index, :show]




  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
    @categories = Category.all
  end

  # GET /paintings/1/edit
  def edit
    @categories = Category.all
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:title, :price, :quantity, :description, :size, :materials, :category_id, :image)
    end
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/paintings/_form.html.erb
<%= form_for(@painting) do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, placeholder: "Image", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :price, placeholder: "Price", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.number_field :quantity, placeholder: "Quantity", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :size, placeholder: "Size", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :materials, placeholder: "Materials", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select(:category_id, @categories.collect {|c| [c.name, c.id]}, {include_blank: "Sold or For Sale?"}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form' %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', paintings_path %>

app/views/paintings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Paintings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Size</th>
      <th>Materials</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paintings.each do |painting| %>
      <tr>
        <td><%= painting.title %></td>
        <td><%= image_tag painting.image.url(:thumb) %></td>
        <td><%= number_to_currency painting.price %></td>
        <td><%= painting.quantity %></td>
        <td><%= painting.description %></td>
        <td><%= painting.size %></td>
        <td><%= painting.materials %></td>
        <td><%= painting.category_id %></td>
        <td><%= link_to 'Show', painting %></td>
        <td><%= link_to 'Edit', edit_painting_path(painting) %></td>
        <td><%= link_to 'Destroy', painting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Painting', new_painting_path %>

app/views/paintings/new.html.erb
<h1>New Painting</h1>

<%= render 'form' %>

<%= link_to 'Back', paintings_path %>


<p>&nbsp</p>
<p>&nbsp</p>
<p>&nbsp</p>

app/views/paintings/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @painting.title %></h1>

  <p><%= image_tag @painting.image.url(:medium) %></p>

  <p><%= number_to_currency @painting.price %></p>

  <p><%= @painting.description %></p>

  <p>
    <strong>Dimensions:</strong>
    <%= @painting.size %>
  </p>

  <p>
    <strong>Materials:</strong>
    <%= @painting.materials %>
  </p>
  
  <p>
    <%= form_tag('/add_to_cart') do %>

    <%= submit_tag "Add To Cart", class: "btn btn-info" %>
    <% end %>
  </p>

<% if can? :update, @article %>
<%= link_to 'Edit', edit_painting_path(@painting) %> |
<% end %>
<%= link_to 'Back', root_path %>

<p>&nbsp</p>
<p>&nbsp</p>
<p>&nbsp</p>