config/routes.rb
Rails.application.routes.draw do

  get 'charges/create'

  get 'charges/new'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  post 'order_complete' => 'cart#order_complete'

  post 'checkout' => 'cart#checkout'

  resources :orders
  resources :line_items
  devise_for :users
  resources :paintings
  
  root 'welcome#index'
  get 'contact' => 'welcome#contact'
  get 'sold' => 'welcome#sold'
  get 'for_sale' => 'welcome#for_sale'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtGallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
     <link rel="shortcut icon" href="/favicon.ico">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

     <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
      <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
      <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
      <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
      <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
      <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
      <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
      <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
      <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
      <link rel="icon" type="image/png" href="/favicon-194x194.png" sizes="194x194">
      <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
      <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
      <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
      <link rel="manifest" href="/manifest.json">
      <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
      <meta name="msapplication-TileColor" content="#da532c">
      <meta name="msapplication-TileImage" content="/mstile-144x144.png">
      <meta name="theme-color" content="#ffffff">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= mail_to "leilajacob@me.com", "Contact" %></li>
        <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> For Sale <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @categories.each do |cat| %>
              <li><%= link_to cat.name, for_sale_path(cat_id: cat.id) %></li>
            <% end %>
          </ul>
        </li>   
      </ul>

      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %> 
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>

      </ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>

<div class="container">



<!--    <div class="col-md-2 center-it">
      <% if user_signed_in? %> 
        <%= link_to view_order_path do %>

         <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>

        <% end %>

      <% else %>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Log In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            </ul>
          </div>
      <% end %>
-->


  <%= yield %>
</div>

        <div class="mastfoot">
            <div class="inner">
              <a href="https://instagram.com/leila.jacob/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-instagram fa-stack-1x"></i>
        </span>
        <a href="https://www.pinterest.com/asganymede/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-pinterest fa-stack-1x"></i>
        </span>
        <a href="https://twitter.com/leila_jacob" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-twitter fa-stack-1x"></i>
        </span>
        <a href="https://www.youtube.com/channel/UCdU1vd_pVw83Yec1FfdgTyQ?view_as=public" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-youtube fa-stack-1x"></i>
        </span>
        <a href="http://leilajacob.deviantart.com/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-deviantart fa-stack-1x"></i>
        </span>
        <a href="http://rosalindasganymede.tumblr.com/" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-tumblr fa-stack-1x"></i>
        </span>
        <a href="https://github.com/leilajacob" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-github-square fa-stack-1x"></i>
        </span>
        <!-- <a href=""><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-slack fa-stack-1x"></i>
        </span> -->
        <a href="https://www.linkedin.com/profile/view?id=AAMAABWcluUB2lmuExk-XtJMBws1Y2c-i4gW9sw&trk=hp-identity-name" target="_blank"><span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-linkedin fa-stack-1x"></i>
        </span>
            </div>
</body>
</html>